name: MoreCommands
main: GlaciercreepsMC\morecommands\MoreCommands
version: 1.1.0
api: [1.10.0, 1.11.0, 1.12.0]
description: Adds more commands for moderators and admins
commands:
    gms:
        usage: /gms
        description: Changes gamemode to survival
    gmc:
        usage: /gmc
        description: Changes gamemode to creative
    gma:
        usage: /gma
        description: Changes gamemode to adventure
    gmspc:
        usage: /gmspc
        description: Changes gamemode to spectator
    slay:
        usage: /slay <player>
        description: Slays the specified player
    heal:
        usage: /heal [player]
        description: Heals you or a specified player
    last:
        usage: /last [count] or /last history
        description: Repeats last command. If count (a number) is supplied, it repeats the nth last command
    uuid:
        usage: /uuid
        description: Shows your uuid and id
        
permissions:
    morecommands.heal:
        default: op
        description: Allows you to heal yourself or others
    morecommands.gmc:
        default: op
        description: Lets you use /gmc
    morecommands.gms:
        default: op
        description: Lets you use /gms
    morecommands.gma:
        default: op
        description: Lets you use /gma
    morecommands.gmspc:
        default: op
        description: Lets you use /gmspc
    morecommands.slay:
        default: op
        description: Lets you /slay others
    morecommands.uuid:
        default: op
        description: Lets you look at your uuid and entity id