name: MoreCommands
main: GlaciercreepsMC\morecommands\MoreCommands
version: 1.0.2
api: [1.4.0, 1.6.0, 1.7.0, 1.9.0, 1.10.0, 1.12.0]
description: Adds more commands for moderators and admins
commands:
    gms:
        usage: /gms
        description: Changes gamemode to survival
    gmc:
        usage: /gmc
        description: Changes gamemode to creative
    gma:
        usage: /gma
        description: Changes gamemode to adventure
    gmspc:
        usage: /gmspc
        description: Changes gamemode to spectator
    slay:
        usage: /slay <player>
        description: Slays the specified player
    heal:
        usage: /heal [player]
        description: Heals you or a specified player
    mute:
        usage: /mute <player>
        description: Mutes a player
    unmute:
        usage: /unmute <player>
        description: Unmutes a player
    freeze:
        usage: /freeze <player>
        description: Freezes a player so they cant move
    unfreeze:
        usage: /unfreeze <player>
        description: Unfreezes a player
permissions:
    morecommands.heal:
        default: op
        description: Allows you to heal yourself or others
    morecommands.mute:
        default: op
        description: Allows you to mute other players
    morecommands.unmute:
        default: op
        description: Allows you to unmute muted players
    morecommands.freeze:
        default: op
        description: Allows you to freeze others
    morecommands.unfreeze:
        default: op
        description: Allows you to unfreeze others
    morecommands.gmc:
        default: op
        description: Lets you use /gmc
    morecommands.gms:
        default: op
        description: Lets you use /gms
    morecommands.gma:
        default: op
        description: Lets you use /gma
    morecommands.gmspc:
        default: op
        description: Lets you use /gmspc
    morecommands.slay:
        default: op
        description: Lets you /slay others
